"""empty message

Revision ID: 902d3b4024a7
Revises: 
Create Date: 2022-11-30 12:52:04.601915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '902d3b4024a7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_result', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot', sa.BLOB(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('poll_result', schema=None) as batch_op:
        batch_op.drop_column('plot')

    # ### end Alembic commands ###
